### ISSUE TITLE
Enable nats authentication by service account and clients secret

### ISSUE THREAD

**Issue by zuiurs** [kubernetes-native-testbed/kubernetes-native-testbed#344]
I apply manifests below to enable authentication on NATS, but NATS returned `failed to create connection to delivery status queue: nats: Authorization Violation (delivery-status-queue.delivery-status.svc.cluster.local:4222 (user=order, password=order))`.

```yaml
---
apiVersion: nats.io/v1alpha2
kind: NatsCluster
metadata:
  name: delivery-status-queue
  namespace: delivery-status
  labels:
    service: delivery-status
    role: queue
spec:
  size: 3
  version: "1.2.0"
  pod:
    enableConfigReload: true
  auth:
    clientsAuthSecret: "nats-clients-auth"
---
apiVersion: v1
kind: Secret
metadata:
  name: nats-clients-auth
  namespace: delivery-status
  labels:
    service: delivery-status
    role: queue
stringData:
  clients-auth.json: |-
    {
      "users": [
        { "username": "order", "password": "order",
          "permissions": {
            "publish": [">"],
            "subscribe": [">"]
          }
        }
      ],
      "default_permissions": {
        "publish": ["SANDBOX.*"],
        "subscribe": ["PUBLIC.>"]
      }
    }
```

Go code for connection to NATS.

```go
qconn, err := nats.Connect(
    deliveryStatusHost+":"+deliveryStatusPort,
    nats.UserInfo(deliveryStatusUsername, deliveryStatusPassword),
)
```

related commit: 2f43d7399b9054b52a3eed3a8e1e1e6d50c069c3
