### ISSUE TITLE
remove redundant httpproxy settings

### ISSUE THREAD

**Issue by MasayaAoyama** [kubernetes-native-testbed/kubernetes-native-testbed#385]
from

```
    - services:
        - name: payment-info
          port: 8080
      conditions:
        - prefix: /payment-info
      pathRewritePolicy:
        replacePrefix:
          - replacement: /payment-info
      permitInsecure: true
```

to

```
    - services:
        - name: payment-info
          port: 8080
      conditions:
        - prefix: /
      pathRewritePolicy:
        replacePrefix:
          - replacement: /
      permitInsecure: true

```
